// <auto-generated />
// Generated by scripts/generate-open-with-policy.mjs from ipc/schema/v1/open-with-policy.json.

namespace SimpleFile.Core;

internal static class OpenWithPolicyGenerated
{
    public static readonly string[] DeniedTargetExtensions =
    [
        ".bat",
        ".cmd",
        ".com",
        ".cpl",
        ".dll",
        ".exe",
        ".hta",
        ".inf",
        ".ins",
        ".iso",
        ".jar",
        ".js",
        ".jse",
        ".lnk",
        ".msc",
        ".msi",
        ".msp",
        ".pif",
        ".ps1",
        ".ps1xml",
        ".ps2",
        ".ps2xml",
        ".psc1",
        ".psc2",
        ".reg",
        ".scr",
        ".sct",
        ".sh",
        ".sys",
        ".vb",
        ".vbe",
        ".vbs",
        ".ws",
        ".wsc",
        ".wsf",
        ".wsh",
    ];
}
