using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Shapes;

namespace SimpleFile.App;

public sealed partial class MainWindow
{
    private Grid SidebarRoot => SidebarPanel.Root;
    private Border SidebarTargetSwitch => SidebarPanel.TargetSwitch;
    private Button SidebarLeftButton => SidebarPanel.LeftButton;
    private Button SidebarRightButton => SidebarPanel.RightButton;
    private Button SidebarCloseButton => SidebarPanel.CloseButton;
    private StackPanel QuickAccessSection => SidebarPanel.QuickAccessSectionRoot;
    private Button QuickAccessCollapseButton => SidebarPanel.QuickAccessCollapse;
    private ListView QuickAccessList => SidebarPanel.QuickAccess;
    private Button RefreshDrivesButton => SidebarPanel.RefreshDrives;
    private Button MyPcCollapseButton => SidebarPanel.MyPcCollapse;
    private ListView DriveList => SidebarPanel.DriveItems;
    private StackPanel FolderTreeSection => SidebarPanel.FolderTreeSectionRoot;
    private TextBlock FolderTreeEmptyText => SidebarPanel.FolderTreeEmpty;
    private ListView FolderTreeList => SidebarPanel.FolderTree;
    private StackPanel BookmarksSection => SidebarPanel.BookmarksSectionRoot;
    private TextBlock BookmarksEmptyText => SidebarPanel.BookmarksEmpty;
    private ListView BookmarksList => SidebarPanel.Bookmarks;
    private StackPanel RecentSection => SidebarPanel.RecentSectionRoot;
    private Button ClearRecentsButton => SidebarPanel.ClearRecents;
    private TextBlock RecentsEmptyText => SidebarPanel.RecentsEmpty;
    private ListView RecentsList => SidebarPanel.Recents;
    private StackPanel SmartFoldersSection => SidebarPanel.SmartFoldersSectionRoot;
    private TextBlock SmartFoldersEmptyText => SidebarPanel.SmartFoldersEmpty;
    private ListView SmartFoldersList => SidebarPanel.SmartFolders;

    private Grid PrimaryToolbar => PrimaryToolbarPanel.ToolbarRoot;
    private ColumnDefinition PrimarySearchColumn => PrimaryToolbarPanel.SearchColumn;
    private ColumnDefinition PrimaryActionsColumn => PrimaryToolbarPanel.ActionsColumn;
    private StackPanel PrimaryNavHost => PrimaryToolbarPanel.NavHost;
    private Button PrimarySidebarToggleButton => PrimaryToolbarPanel.SidebarToggleButton;
    private Button PrimaryBackButton => PrimaryToolbarPanel.BackButton;
    private Button PrimaryForwardButton => PrimaryToolbarPanel.ForwardButton;
    private Button PrimaryUpButton => PrimaryToolbarPanel.UpButton;
    private Grid PrimarySearchHost => PrimaryToolbarPanel.SearchHost;
    private TextBox SearchBox => PrimaryToolbarPanel.SearchTextBox;
    private ToggleButton ContentSearchButton => PrimaryToolbarPanel.ContentSearchToggle;
    private Button SearchCancelButton => PrimaryToolbarPanel.SearchCancel;
    private StackPanel PrimaryActionsHost => PrimaryToolbarPanel.ActionsHost;
    private TextBox QuickFilterBox => PrimaryToolbarPanel.QuickFilterTextBox;
    private Button PrimaryNewFolderButton => PrimaryToolbarPanel.NewFolderButton;
    private Button PrimaryNewFileButton => PrimaryToolbarPanel.NewFileButton;
    private Button DualPaneButton => PrimaryToolbarPanel.DualPaneToggleButton;
    private Button ClosePrimaryPaneButton => PrimaryToolbarPanel.ClosePaneButton;
    private Button WorkspaceProfileButton => PrimaryToolbarPanel.ProfileButton;
    private StackPanel WorkspaceProfilesHost => PrimaryToolbarPanel.WorkspaceProfilesList;
    private Button PrimaryViewButton => PrimaryToolbarPanel.ViewButton;
    private Button ViewDualPaneButton => PrimaryToolbarPanel.ViewDualPaneToggleButton;
    private FontIcon ViewDualPaneIcon => PrimaryToolbarPanel.ViewDualPaneGlyph;
    private TextBlock ViewDualPaneText => PrimaryToolbarPanel.ViewDualPaneLabel;
    private RadioButtons ViewStyleRadioButtons => PrimaryToolbarPanel.ViewStyleOptions;
    private TextBlock ViewIconSizeValueText => PrimaryToolbarPanel.ViewIconSizeValue;
    private Slider ViewIconSizeSlider => PrimaryToolbarPanel.ViewIconSize;
    private Button ViewApplyBothButton => PrimaryToolbarPanel.ViewApplyBoth;
    private Button ViewUseGloballyButton => PrimaryToolbarPanel.ViewUseGlobally;
    private Button ViewUseForFolderButton => PrimaryToolbarPanel.ViewUseForFolder;
    private Button ViewUseForDescendantsButton => PrimaryToolbarPanel.ViewUseForDescendants;
    private TextBlock ViewFolderRuleStatusText => PrimaryToolbarPanel.ViewFolderRuleStatus;
    private Button ViewSaveProfileButton => PrimaryToolbarPanel.ViewSaveProfile;
    private StackPanel ViewProfilesHost => PrimaryToolbarPanel.ViewProfilesList;
    private Button PrimarySettingsButton => PrimaryToolbarPanel.SettingsButton;
    private Button PrimaryMoreButton => PrimaryToolbarPanel.MoreButton;

    private Grid PrimaryPaneRoot => PrimaryPane.Root;
    private Border PrimaryActivePaneRail => PrimaryPane.ActivePaneRail;
    private Grid PrimaryPaneHeader => PrimaryPane.PaneHeader;
    private StackPanel PrimaryPaneCaption => PrimaryPane.PaneCaption;
    private Rectangle PrimaryPaneCaptionRail => PrimaryPane.PaneCaptionRail;
    private TextBlock PrimaryPaneCaptionText => PrimaryPane.PaneCaptionText;
    private StackPanel PrimaryTabHost => PrimaryPane.TabHost;
    private Grid PrimaryPathBar => PrimaryPane.PathBar;
    private ScrollViewer PrimaryBreadcrumbScroller => PrimaryPane.BreadcrumbScroller;
    private StackPanel PrimaryBreadcrumbHost => PrimaryPane.BreadcrumbHost;
    private TextBox PrimaryPathInput => PrimaryPane.PathInput;
    private Button PrimaryEditPathButton => PrimaryPane.EditPathButton;
    private ScrollViewer PrimaryColumnHeaderScroller => PrimaryPane.ColumnHeaderScroller;
    private Grid PrimaryColumnHeader => PrimaryPane.ColumnHeader;
    private ListView PrimaryFileList => PrimaryPane.FileList;
    private Canvas PrimaryMarqueeCanvas => PrimaryPane.MarqueeCanvas;
    private Rectangle PrimaryMarqueeRect => PrimaryPane.MarqueeRect;
    private StackPanel PrimaryEmptyState => PrimaryPane.EmptyState;
    private TextBlock PrimaryEmptyTitle => PrimaryPane.EmptyTitle;
    private TextBlock PrimaryEmptyHint => PrimaryPane.EmptyHint;

    private Grid SecondaryPaneRoot => SecondaryPane.Root;
    private Border SecondaryActivePaneRail => SecondaryPane.ActivePaneRail;
    private Grid SecondaryPaneHeader => SecondaryPane.PaneHeader;
    private StackPanel SecondaryPaneCaption => SecondaryPane.PaneCaption;
    private Rectangle SecondaryPaneCaptionRail => SecondaryPane.PaneCaptionRail;
    private TextBlock SecondaryPaneCaptionText => SecondaryPane.PaneCaptionText;
    private StackPanel SecondaryTabHost => SecondaryPane.TabHost;
    private Grid SecondaryPathBar => SecondaryPane.PathBar;
    private ScrollViewer SecondaryBreadcrumbScroller => SecondaryPane.BreadcrumbScroller;
    private StackPanel SecondaryBreadcrumbHost => SecondaryPane.BreadcrumbHost;
    private TextBox SecondaryPathInput => SecondaryPane.PathInput;
    private Button SecondaryEditPathButton => SecondaryPane.EditPathButton;
    private ScrollViewer SecondaryColumnHeaderScroller => SecondaryPane.ColumnHeaderScroller;
    private Grid SecondaryColumnHeader => SecondaryPane.ColumnHeader;
    private ListView SecondaryFileList => SecondaryPane.FileList;
    private Canvas SecondaryMarqueeCanvas => SecondaryPane.MarqueeCanvas;
    private Rectangle SecondaryMarqueeRect => SecondaryPane.MarqueeRect;
    private StackPanel SecondaryEmptyState => SecondaryPane.EmptyState;
    private TextBlock SecondaryEmptyTitle => SecondaryPane.EmptyTitle;
    private TextBlock SecondaryEmptyHint => SecondaryPane.EmptyHint;

    private Border PreviewPane => PreviewPanel.PaneRoot;
    private TextBlock PreviewTitle => PreviewPanel.TitleText;
    private TextBlock PreviewSubtitle => PreviewPanel.SubtitleText;
    private Button PreviewOpenButton => PreviewPanel.OpenButton;
    private Button PreviewOpenWithButton => PreviewPanel.OpenWithButton;
    private Button PreviewRevealButton => PreviewPanel.RevealButton;
    private Button PreviewCompareButton => PreviewPanel.CompareButton;
    private Button PreviewChecksumButton => PreviewPanel.ChecksumButton;
    private StackPanel PreviewIconPanel => PreviewPanel.IconPanel;
    private Image PreviewIconImage => PreviewPanel.IconImage;
    private TextBlock PreviewIconLabel => PreviewPanel.IconLabel;
    private Image PreviewImage => PreviewPanel.ImagePreview;
    private WebView2 PreviewPdfWebView => PreviewPanel.PdfPreview;
    private MediaPlayerElement PreviewMediaPlayer => PreviewPanel.MediaPreview;
    private TextBox PreviewTextBox => PreviewPanel.TextPreview;
    private TextBlock PreviewEmptyText => PreviewPanel.EmptyText;
    private StackPanel PreviewMetadataRows => PreviewPanel.MetadataRows;
    private TextBlock PreviewChecksumText => PreviewPanel.ChecksumText;

    private void AttachControlEvents()
    {
        SidebarPanel.SidebarLeft += OnSidebarLeft;
        SidebarPanel.SidebarRight += OnSidebarRight;
        SidebarPanel.ToggleSidebar += OnToggleSidebar;
        SidebarPanel.ToggleQuickAccess += OnToggleQuickAccess;
        SidebarPanel.QuickAccessClick += OnQuickAccessClick;
        SidebarPanel.RefreshDrivesClick += OnRefreshDrives;
        SidebarPanel.ToggleMyPc += OnToggleMyPc;
        SidebarPanel.DriveClick += OnDriveClick;
        SidebarPanel.RefreshFolderTree += OnRefreshFolderTree;
        SidebarPanel.FolderTreeClick += OnFolderTreeClick;
        SidebarPanel.FolderTreeToggle += OnFolderTreeToggle;
        SidebarPanel.AddBookmark += OnAddBookmark;
        SidebarPanel.BookmarkClick += OnBookmarkClick;
        SidebarPanel.RemoveBookmark += OnRemoveBookmark;
        SidebarPanel.ClearRecentHistory += OnClearRecentHistory;
        SidebarPanel.RecentClick += OnRecentClick;
        SidebarPanel.SaveSmartFolder += OnSaveSmartFolder;
        SidebarPanel.SmartFolderClicked += OnSmartFolderClicked;
        SidebarPanel.DeleteSmartFolderClicked += OnDeleteSmartFolderClicked;

        PrimaryToolbarPanel.PrimaryToolbarSizeChanged += OnPrimaryToolbarSizeChanged;
        PrimaryToolbarPanel.ToggleSidebar += OnToggleSidebar;
        PrimaryToolbarPanel.PrimaryBack += OnPrimaryBack;
        PrimaryToolbarPanel.PrimaryForward += OnPrimaryForward;
        PrimaryToolbarPanel.PrimaryUp += OnPrimaryUp;
        PrimaryToolbarPanel.SearchKeyDown += OnSearchKeyDown;
        PrimaryToolbarPanel.SearchClick += OnSearchClick;
        PrimaryToolbarPanel.ContentSearchToggleClick += OnContentSearchToggle;
        PrimaryToolbarPanel.CancelSearchClick += OnCancelSearchClick;
        PrimaryToolbarPanel.QuickFilterChanged += OnQuickFilterChanged;
        PrimaryToolbarPanel.PrimaryNewFolder += OnPrimaryNewFolder;
        PrimaryToolbarPanel.PrimaryNewFile += OnPrimaryNewFile;
        PrimaryToolbarPanel.ToggleDualPane += OnToggleDualPane;
        PrimaryToolbarPanel.ClosePrimaryPane += OnClosePrimaryPane;
        PrimaryToolbarPanel.WorkspaceProfilesFlyoutOpening += (sender, e) => OnWorkspaceProfilesFlyoutOpening(sender!, e);
        PrimaryToolbarPanel.WorkspaceProfileSaveClicked += OnWorkspaceProfileSaveClicked;
        PrimaryToolbarPanel.WorkspaceProfileManageClicked += OnWorkspaceProfileManageClicked;
        PrimaryToolbarPanel.ViewOptionsFlyoutOpening += (sender, e) => OnViewOptionsFlyoutOpening(sender!, e);
        PrimaryToolbarPanel.ViewDualPaneClicked += OnViewDualPaneClicked;
        PrimaryToolbarPanel.ViewStyleSelectionChanged += OnViewStyleSelectionChanged;
        PrimaryToolbarPanel.ViewIconSizeSliderChanged += OnViewIconSizeSliderChanged;
        PrimaryToolbarPanel.ViewApplyBothClicked += OnViewApplyBothClicked;
        PrimaryToolbarPanel.ViewUseGloballyClicked += OnViewUseGloballyClicked;
        PrimaryToolbarPanel.ViewUseForFolderClicked += OnViewUseForFolderClicked;
        PrimaryToolbarPanel.ViewUseForDescendantsClicked += OnViewUseForDescendantsClicked;
        PrimaryToolbarPanel.ViewSaveProfileClicked += OnViewSaveProfileClicked;
        PrimaryToolbarPanel.SettingsClicked += OnSettingsClicked;
        PrimaryToolbarPanel.PrimaryMoreMenuOpening += (sender, e) => OnPrimaryMoreMenuOpening(sender!, e);

        PrimaryPane.PathKeyDown += OnPrimaryPathKeyDown;
        PrimaryPane.PathLostFocus += OnPrimaryPathLostFocus;
        PrimaryPane.PathTextChanged += OnPrimaryPathTextChanged;
        PrimaryPane.EditPath += OnEditPrimaryPath;
        PrimaryPane.MarqueePressed += OnPrimaryMarqueePressed;
        PrimaryPane.MarqueePointerMoved += OnMarqueePointerMoved;
        PrimaryPane.MarqueePointerReleased += OnMarqueePointerReleased;
        PrimaryPane.MarqueePointerCanceled += OnMarqueePointerCanceled;
        PrimaryPane.FileDoubleTapped += OnPrimaryFileDoubleTapped;
        PrimaryPane.FileDragItemsStarting += OnFileDragItemsStarting;
        PrimaryPane.FileDragItemsCompleted += OnFileDragItemsCompleted;
        PrimaryPane.FileDragLeave += OnFileDragLeave;
        PrimaryPane.FileDragOver += OnPrimaryFileDragOver;
        PrimaryPane.FileDrop += OnPrimaryFileDrop;
        PrimaryPane.FileKeyDown += OnPrimaryFileKeyDown;
        PrimaryPane.FileRightTapped += OnPrimaryFileRightTapped;
        PrimaryPane.FileSelectionChanged += OnPrimarySelectionChanged;
        PrimaryPane.FileListContextOpening += (sender, e) => OnPrimaryFileListContextOpening(sender!, e);
        PrimaryPane.FileRowContextRequested += (sender, e) => OnFileRowContextRequested(sender!, e);

        SecondaryPane.PathKeyDown += OnSecondaryPathKeyDown;
        SecondaryPane.PathLostFocus += OnSecondaryPathLostFocus;
        SecondaryPane.PathTextChanged += OnSecondaryPathTextChanged;
        SecondaryPane.EditPath += OnEditSecondaryPath;
        SecondaryPane.MarqueePressed += OnSecondaryMarqueePressed;
        SecondaryPane.MarqueePointerMoved += OnMarqueePointerMoved;
        SecondaryPane.MarqueePointerReleased += OnMarqueePointerReleased;
        SecondaryPane.MarqueePointerCanceled += OnMarqueePointerCanceled;
        SecondaryPane.FileDoubleTapped += OnSecondaryFileDoubleTapped;
        SecondaryPane.FileDragItemsStarting += OnFileDragItemsStarting;
        SecondaryPane.FileDragItemsCompleted += OnFileDragItemsCompleted;
        SecondaryPane.FileDragLeave += OnFileDragLeave;
        SecondaryPane.FileDragOver += OnSecondaryFileDragOver;
        SecondaryPane.FileDrop += OnSecondaryFileDrop;
        SecondaryPane.FileKeyDown += OnSecondaryFileKeyDown;
        SecondaryPane.FileRightTapped += OnSecondaryFileRightTapped;
        SecondaryPane.FileSelectionChanged += OnSecondarySelectionChanged;
        SecondaryPane.FileListContextOpening += (sender, e) => OnSecondaryFileListContextOpening(sender!, e);
        SecondaryPane.FileRowContextRequested += (sender, e) => OnFileRowContextRequested(sender!, e);

        PreviewPanel.TogglePreview += OnTogglePreview;
        PreviewPanel.PreviewOpenClick += OnPreviewOpenClick;
        PreviewPanel.PreviewOpenWithClick += OnPreviewOpenWithClick;
        PreviewPanel.PreviewRevealClick += OnPreviewRevealClick;
        PreviewPanel.PreviewCompareClick += OnPreviewCompareClick;
        PreviewPanel.PreviewChecksumClick += OnPreviewChecksumClick;
    }
}
