// <auto-generated />
// Generated by scripts/generate-ipc-bindings.mjs from ipc/schema/v1.
#nullable enable
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace SimpleFile.Ipc;

public sealed partial class NamedPipeJsonClient
{
    public Task<HealthResult> HealthAsync(CancellationToken cancellationToken = default)
        => InvokeAsync<HealthResult>(Protocol.HealthMethod, new { }, cancellationToken);

    public Task ShutdownAsync(CancellationToken cancellationToken = default)
        => InvokeAsync(Protocol.ShutdownMethod, new { }, cancellationToken);

    public Task<string> GetAppVersionAsync(CancellationToken cancellationToken = default)
        => InvokeAsync<string>(Protocol.GetAppVersionMethod, new { }, cancellationToken);

    public Task<string> GetHomeDirAsync(CancellationToken cancellationToken = default)
        => InvokeAsync<string>(Protocol.GetHomeDirMethod, new { }, cancellationToken);

    public async Task<IReadOnlyList<DriveInfo>> ListDrivesAsync(CancellationToken cancellationToken = default)
    {
        var drives = await InvokeAsync<DriveInfo[]>(Protocol.ListDrivesMethod, new { }, cancellationToken)
            .ConfigureAwait(false);
        return drives;
    }

    public async Task<IReadOnlyList<DriveInfo>> ListDrivesLightAsync(CancellationToken cancellationToken = default)
    {
        var drives = await InvokeAsync<DriveInfo[]>(Protocol.ListDrivesMethod, new { mode = "light" }, cancellationToken)
            .ConfigureAwait(false);
        return drives;
    }

    public Task SelectDirectoryAsync(string? defaultPath = null, CancellationToken cancellationToken = default)
        => InvokeAsync(Protocol.SelectDirectoryMethod, new SelectDirectoryParams { DefaultPath = defaultPath }, cancellationToken);

    public Task ShowMainWindowAsync(CancellationToken cancellationToken = default)
        => InvokeAsync(Protocol.ShowMainWindowMethod, new { }, cancellationToken);

    public Task<string?> GetDbSettingAsync(string key, CancellationToken ct = default)
        => InvokeAsync<string?>(Protocol.GetDbSettingMethod, new { key }, ct);

    public Task<Dictionary<string, string?>> GetDbSettingsAsync(string[] keys, CancellationToken ct = default)
        => InvokeAsync<Dictionary<string, string?>>(Protocol.GetDbSettingsMethod, new { keys }, ct);

    public Task SetDbSettingAsync(string key, string value, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.SetDbSettingMethod, new { key, value }, ct);

    public Task<RemoteProfile[]> RemoteListProfilesAsync(CancellationToken ct = default)
        => InvokeAsync<RemoteProfile[]>(Protocol.RemoteListProfilesMethod, new { }, ct);

    public Task<RemoteProfile> RemoteSaveProfileAsync(RemoteProfileInput profile, string? secret = null, CancellationToken ct = default)
        => InvokeAsync<RemoteProfile>(Protocol.RemoteSaveProfileMethod, new { profile, secret }, ct);

    public Task RemoteDeleteProfileAsync(string profileId, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.RemoteDeleteProfileMethod, new { profileId }, ct);

    public Task<RemoteConnectionTestResult> RemoteTestProfileAsync(RemoteProfileInput profile, string? secret = null, CancellationToken ct = default)
        => InvokeAsync<RemoteConnectionTestResult>(Protocol.RemoteTestProfileMethod, new { profile, secret }, ct);

    public Task<RemoteSession> RemoteConnectAsync(string profileId, string? secret = null, CancellationToken ct = default)
        => InvokeAsync<RemoteSession>(Protocol.RemoteConnectMethod, new { profileId, secret }, ct);

    public Task RemoteDisconnectAsync(string remoteSessionId, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.RemoteDisconnectMethod, new { remoteSessionId }, ct);

    public Task<DirectoryListing> RemoteListDirectoryAsync(string remoteSessionId, string path, CancellationToken ct = default)
        => InvokeAsync<DirectoryListing>(Protocol.RemoteListDirectoryMethod, new { remoteSessionId, path }, ct);

    public Task<FileEntry> RemoteCreateDirectoryAsync(string remoteSessionId, string path, string name, CancellationToken ct = default)
        => InvokeAsync<FileEntry>(Protocol.RemoteCreateDirectoryMethod, new { remoteSessionId, path, name }, ct);

    public Task<FileEntry> RemoteRenameEntryAsync(string remoteSessionId, string path, string newName, CancellationToken ct = default)
        => InvokeAsync<FileEntry>(Protocol.RemoteRenameEntryMethod, new { remoteSessionId, path, newName }, ct);

    public Task<string[]> RemoteDeleteEntriesAsync(string remoteSessionId, string[] paths, CancellationToken ct = default)
        => InvokeAsync<string[]>(Protocol.RemoteDeleteEntriesMethod, new { remoteSessionId, paths }, ct);

    public Task<string> RemoteDownloadFileAsync(string remoteSessionId, string remotePath, string localPath, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.RemoteDownloadFileMethod, new { remoteSessionId, remotePath, localPath }, ct);

    public Task<FileEntry> RemoteUploadFileAsync(string remoteSessionId, string localPath, string remotePath, CancellationToken ct = default)
        => InvokeAsync<FileEntry>(Protocol.RemoteUploadFileMethod, new { remoteSessionId, localPath, remotePath }, ct);

    public Task<string> CreateDirectoryAsync(string path, string name, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.CreateDirectoryMethod, new { path, name }, ct);

    public Task<string> CreateFileAsync(string path, string name, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.CreateFileMethod, new { path, name }, ct);

    public Task<string> CreateShortcutAsync(string path, string name, string targetPath, string? arguments = null, string? workingDirectory = null, string? iconPath = null, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.CreateShortcutMethod, new { path, name, targetPath, arguments, workingDirectory, iconPath }, ct);

    public Task DeleteEntryAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.DeleteEntryMethod, new { path }, ct);

    public Task<string[]> MoveToTrashAsync(string[] paths, CancellationToken ct = default)
        => InvokeAsync<string[]>(Protocol.MoveToTrashMethod, new { paths }, ct);

    public Task<string[]> RestoreRecycleBinAsync(string[] paths, CancellationToken ct = default)
        => InvokeAsync<string[]>(Protocol.RestoreRecycleBinMethod, new { paths }, ct);

    public Task EmptyRecycleBinAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.EmptyRecycleBinMethod, new { }, ct);

    public Task<string> RenameEntryAsync(string path, string newName, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.RenameEntryMethod, new { path, newName }, ct);

    public Task<string[]> BatchRenameAsync(RenameRequest[] entries, CancellationToken ct = default)
        => InvokeAsync<string[]>(Protocol.BatchRenameMethod, new { entries }, ct);

    public Task<string> CopyEntryAsync(string source, string destination, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.CopyEntryMethod, new { source, destination }, ct);

    public Task<string> MoveEntryAsync(string source, string destination, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.MoveEntryMethod, new { source, destination }, ct);

    public Task<string> CopyEntryResolvedAsync(string source, string destination, string conflictAction, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.CopyEntryResolvedMethod, new { source, destination, conflictAction }, ct);

    public Task<string> MoveEntryResolvedAsync(string source, string destination, string conflictAction, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.MoveEntryResolvedMethod, new { source, destination, conflictAction }, ct);

    public Task<FileEntry> GetEntryInfoAsync(string path, CancellationToken ct = default)
        => InvokeAsync<FileEntry>(Protocol.GetEntryInfoMethod, new { path }, ct);

    public Task OpenFileAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.OpenFileMethod, new { path }, ct);

    public Task RevealInFolderAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.RevealInFolderMethod, new { path }, ct);

    public Task OpenExternalUrlAsync(string url, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.OpenExternalUrlMethod, new { url }, ct);

    public Task<ArchiveInfo> ListArchiveAsync(string path, CancellationToken ct = default)
        => InvokeAsync<ArchiveInfo>(Protocol.ListArchiveMethod, new { path }, ct);

    public Task<ArchiveCapabilities> GetArchiveCapabilitiesAsync(CancellationToken ct = default)
        => InvokeAsync<ArchiveCapabilities>(Protocol.GetArchiveCapabilitiesMethod, new { }, ct);

    public Task ExtractArchiveAsync(string archivePath, string destination, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.ExtractArchiveMethod, new { archivePath, destination }, ct);

    public Task CreateArchiveAsync(string[] paths, string archivePath, string format, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CreateArchiveMethod, new { paths, archivePath, format }, ct);

    public Task<FilePreview> ReadFilePreviewAsync(string path, ulong? maxSize = null, CancellationToken ct = default)
        => InvokeAsync<FilePreview>(Protocol.ReadFilePreviewMethod, new { path, maxSize }, ct);

    public Task<byte[]> GenerateThumbnailAsync(string path, uint size, CancellationToken ct = default)
        => InvokeAsync<byte[]>(Protocol.GenerateThumbnailMethod, new { path, size }, ct);

    public Task<ThumbnailResult[]> GenerateThumbnailsAsync(string[] paths, uint size, CancellationToken ct = default)
        => InvokeAsync<ThumbnailResult[]>(Protocol.GenerateThumbnailsMethod, new { paths, size }, ct);

    public Task OpenFileWithAsync(string path, string application, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.OpenFileWithMethod, new { path, application }, ct);

    public Task<FileComparison> CompareFilesAsync(string pathA, string pathB, CancellationToken ct = default)
        => InvokeAsync<FileComparison>(Protocol.CompareFilesMethod, new { pathA, pathB }, ct);

    public Task<Checksums> ComputeChecksumAsync(string path, CancellationToken ct = default)
        => InvokeAsync<Checksums>(Protocol.ComputeChecksumMethod, new { path }, ct);

    public Task<ImageMetadata> GetImageMetadataAsync(string path, CancellationToken ct = default)
        => InvokeAsync<ImageMetadata>(Protocol.GetImageMetadataMethod, new { path }, ct);

    public Task<FileMetadata> GetFileMetadataAsync(string path, CancellationToken ct = default)
        => InvokeAsync<FileMetadata>(Protocol.GetFileMetadataMethod, new { path }, ct);

    public Task<TreeNode[]> ListSubdirectoriesAsync(string path, CancellationToken ct = default)
        => InvokeAsync<TreeNode[]>(Protocol.ListSubdirectoriesMethod, new { path }, ct);

    public Task<FolderMetrics> GetFolderMetricsAsync(string path, CancellationToken ct = default)
        => InvokeAsync<FolderMetrics>(Protocol.GetFolderMetricsMethod, new { path }, ct);

    public Task<ulong> CalculateFolderSizeAsync(string path, CancellationToken ct = default)
        => InvokeAsync<ulong>(Protocol.CalculateFolderSizeMethod, new { path }, ct);

    public Task<ulong> CountFolderItemsAsync(string path, CancellationToken ct = default)
        => InvokeAsync<ulong>(Protocol.CountFolderItemsMethod, new { path }, ct);

    public Task<TransferResult[]> CopyWithProgressAsync(string[] sources, string destination, string? operationId, string conflictAction, CancellationToken ct = default)
        => InvokeAsync<TransferResult[]>(Protocol.CopyWithProgressMethod, new { sources, destination, operationId, conflictAction }, ct);

    public Task<TransferResult[]> MoveWithProgressAsync(string[] sources, string destination, string? operationId, string conflictAction, CancellationToken ct = default)
        => InvokeAsync<TransferResult[]>(Protocol.MoveWithProgressMethod, new { sources, destination, operationId, conflictAction }, ct);

    public Task<bool> CancelOperationAsync(string operationId, CancellationToken ct = default)
        => InvokeAsync<bool>(Protocol.CancelOperationMethod, new { operationId }, ct);

    public Task CancelSearchAsync(string searchId, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelSearchMethod, new { searchId }, ct);

    public Task WatchDirectoryAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.WatchDirectoryMethod, new { path }, ct);

    public Task UnwatchDirectoryAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.UnwatchDirectoryMethod, new { }, ct);

    public Task CancelFolderSizeAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelFolderSizeMethod, new { }, ct);

    public Task CancelFolderItemCountAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelFolderItemCountMethod, new { }, ct);

    public Task CancelCountItemsAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelCountItemsMethod, new { }, ct);

    public Task CancelFolderMetricsAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelFolderMetricsMethod, new { }, ct);

    public Task<CleanupResult> DiskCleanupAsync(string directory, ulong? sizeThreshold, string? operationId, CancellationToken ct = default)
        => InvokeAsync<CleanupResult>(Protocol.DiskCleanupMethod, new { directory, sizeThreshold, operationId }, ct);

    public Task CancelDiskCleanupAsync(string? operationId = null, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelDiskCleanupMethod, new { operationId }, ct);

    public Task<DuplicateCheckResult> DuplicateCheckAsync(string directory, DuplicateScanOptions? options, string? operationId, CancellationToken ct = default)
        => InvokeAsync<DuplicateCheckResult>(Protocol.DuplicateCheckMethod, new { directory, minSize = options?.MinSize, partialHashBytes = options?.PartialHashBytes, maxDepth = options?.MaxDepth, excludePatterns = options?.ExcludePatterns, networkMode = options?.NetworkMode, operationId }, ct);

    public Task CancelDuplicateCheckAsync(string? operationId = null, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.CancelDuplicateCheckMethod, new { operationId }, ct);

    public Task<Tag[]> GetAllTagsAsync(CancellationToken ct = default)
        => InvokeAsync<Tag[]>(Protocol.GetAllTagsMethod, new { }, ct);

    public Task<Tag> CreateTagAsync(string name, string color, CancellationToken ct = default)
        => InvokeAsync<Tag>(Protocol.CreateTagMethod, new { name, color }, ct);

    public Task<Tag> UpdateTagAsync(long id, string name, string color, CancellationToken ct = default)
        => InvokeAsync<Tag>(Protocol.UpdateTagMethod, new { id, name, color }, ct);

    public Task DeleteTagAsync(long id, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.DeleteTagMethod, new { id }, ct);

    public Task<Tag[]> GetTagsForPathAsync(string path, CancellationToken ct = default)
        => InvokeAsync<Tag[]>(Protocol.GetTagsForPathMethod, new { path }, ct);

    public Task SetTagsForPathAsync(string path, long[] tagIds, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.SetTagsForPathMethod, new { path, tagIds }, ct);

    public Task<Dictionary<string, Tag>> GetAllFileTagsAsync(CancellationToken ct = default)
        => InvokeAsync<Dictionary<string, Tag>>(Protocol.GetAllFileTagsMethod, new { }, ct);

    public Task<string[]> GetFilesWithTagAsync(long tagId, CancellationToken ct = default)
        => InvokeAsync<string[]>(Protocol.GetFilesWithTagMethod, new { tagId }, ct);

    public Task<SmartFolder[]> LoadSmartFoldersAsync(CancellationToken ct = default)
        => InvokeAsync<SmartFolder[]>(Protocol.LoadSmartFoldersMethod, new { }, ct);

    public Task<SmartFolder[]> SaveSmartFolderAsync(SmartFolder folder, CancellationToken ct = default)
        => InvokeAsync<SmartFolder[]>(Protocol.SaveSmartFolderMethod, new { folder }, ct);

    public Task<SmartFolder[]> DeleteSmartFolderAsync(string id, CancellationToken ct = default)
        => InvokeAsync<SmartFolder[]>(Protocol.DeleteSmartFolderMethod, new { id }, ct);

    public Task<AppAboutInfo> GetAppAboutInfoAsync(CancellationToken ct = default)
        => InvokeAsync<AppAboutInfo>(Protocol.GetAppAboutInfoMethod, new { }, ct);

    public Task<UpdateInfo?> CheckForUpdateAsync(CancellationToken ct = default)
        => InvokeAsync<UpdateInfo?>(Protocol.CheckForUpdateMethod, new { }, ct);

    public Task InstallUpdateAsync(CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.InstallUpdateMethod, new { }, ct);

    public Task OpenTerminalAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.OpenTerminalMethod, new { path }, ct);

    public Task OpenPowershellAdminAsync(string path, CancellationToken ct = default)
        => InvokeAsync<object?>(Protocol.OpenPowershellAdminMethod, new { path }, ct);

    public Task<GitStatus> GetGitStatusAsync(string path, CancellationToken ct = default)
        => InvokeAsync<GitStatus>(Protocol.GetGitStatusMethod, new { path }, ct);

    public Task<GitRepositoryStatus> GetGitRepositoryStatusAsync(string path, CancellationToken ct = default)
        => InvokeAsync<GitRepositoryStatus>(Protocol.GetGitRepositoryStatusMethod, new { path }, ct);

    public Task<FileEntry[]> GetGitFileStatusesAsync(string path, CancellationToken ct = default)
        => InvokeAsync<FileEntry[]>(Protocol.GetGitFileStatusesMethod, new { path }, ct);

    public Task<GitCommandResult> GitStagePathsAsync(string path, string[] paths, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitStagePathsMethod, new { path, paths }, ct);

    public Task<GitCommandResult> GitUnstagePathsAsync(string path, string[] paths, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitUnstagePathsMethod, new { path, paths }, ct);

    public Task<GitCommandResult> GitDiscardPathsAsync(string path, string[] paths, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitDiscardPathsMethod, new { path, paths }, ct);

    public Task<string> GitDiffPathAsync(string path, string filePath, CancellationToken ct = default)
        => InvokeAsync<string>(Protocol.GitDiffPathMethod, new { path, filePath }, ct);

    public Task<GitCommandResult> GitCommitAsync(string path, string message, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitCommitMethod, new { path, message }, ct);

    public Task<GitCommandResult> GitFetchAsync(string path, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitFetchMethod, new { path }, ct);

    public Task<GitCommandResult> GitPullAsync(string path, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitPullMethod, new { path }, ct);

    public Task<GitCommandResult> GitPushAsync(string path, CancellationToken ct = default)
        => InvokeAsync<GitCommandResult>(Protocol.GitPushMethod, new { path }, ct);
}
