// <auto-generated />
// Generated by scripts/generate-ipc-bindings.mjs from ipc/schema/v1.
#nullable enable
using System.Collections.Generic;

namespace SimpleFile.Ipc;

public static partial class Protocol
{
    public const int DomainMethodCount = 79;
    public const byte BinaryListDirectoryChunk = 1;
    public const byte BinaryListDirectoryResult = 2;
    public const byte BinarySearchResultsBatch = 3;
    public const byte BinarySearchResultsResult = 4;
    public const byte BinaryOperationProgress = 5;
    public const byte BinaryFileChange = 6;
    public const byte BinaryThumbnailResult = 7;
    public const byte BinaryThumbnailsResult = 8;

    public const string HandshakeMethod = "ipc.handshake";
    public const string HealthMethod = "ipc.health";
    public const string ShutdownMethod = "ipc.shutdown";
    public const string GetHomeDirMethod = "get_home_dir";
    public const string SelectDirectoryMethod = "select_directory";
    public const string ListDrivesMethod = "list_drives";
    public const string ListDirectoryMethod = "list_directory";
    public const string ListSubdirectoriesMethod = "list_subdirectories";
    public const string CreateDirectoryMethod = "create_directory";
    public const string CreateFileMethod = "create_file";
    public const string CreateShortcutMethod = "create_shortcut";
    public const string DeleteEntryMethod = "delete_entry";
    public const string MoveToTrashMethod = "move_to_trash";
    public const string RestoreRecycleBinMethod = "restore_recycle_bin";
    public const string EmptyRecycleBinMethod = "empty_recycle_bin";
    public const string RenameEntryMethod = "rename_entry";
    public const string BatchRenameMethod = "batch_rename";
    public const string CopyEntryMethod = "copy_entry";
    public const string MoveEntryMethod = "move_entry";
    public const string CopyEntryResolvedMethod = "copy_entry_resolved";
    public const string MoveEntryResolvedMethod = "move_entry_resolved";
    public const string GetEntryInfoMethod = "get_entry_info";
    public const string CopyWithProgressMethod = "copy_with_progress";
    public const string MoveWithProgressMethod = "move_with_progress";
    public const string CancelOperationMethod = "cancel_operation";
    public const string WatchDirectoryMethod = "watch_directory";
    public const string UnwatchDirectoryMethod = "unwatch_directory";
    public const string ReadFilePreviewMethod = "read_file_preview";
    public const string GenerateThumbnailMethod = "generate_thumbnail";
    public const string GenerateThumbnailsMethod = "generate_thumbnails";
    public const string CalculateFolderSizeMethod = "calculate_folder_size";
    public const string CountFolderItemsMethod = "count_folder_items";
    public const string GetFolderMetricsMethod = "get_folder_metrics";
    public const string CancelFolderSizeMethod = "cancel_folder_size";
    public const string CancelFolderItemCountMethod = "cancel_folder_item_count";
    public const string CancelCountItemsMethod = "cancel_count_items";
    public const string CancelFolderMetricsMethod = "cancel_folder_metrics";
    public const string OpenFileMethod = "open_file";
    public const string RevealInFolderMethod = "reveal_in_folder";
    public const string OpenExternalUrlMethod = "open_external_url";
    public const string ListArchiveMethod = "list_archive";
    public const string ExtractArchiveMethod = "extract_archive";
    public const string CreateArchiveMethod = "create_archive";
    public const string CheckRarInstalledMethod = "check_rar_installed";
    public const string PrepareRarInstallMethod = "prepare_rar_install";
    public const string DiscardRarInstallMethod = "discard_rar_install";
    public const string InstallRarMethod = "install_rar";
    public const string GetDbSettingMethod = "get_db_setting";
    public const string SetDbSettingMethod = "set_db_setting";
    public const string GitPullMethod = "git_pull";
    public const string GitPushMethod = "git_push";
    public const string OpenTerminalMethod = "open_terminal";
    public const string OpenPowershellAdminMethod = "open_powershell_admin";
    public const string SearchFilesMethod = "search_files";
    public const string CancelSearchMethod = "cancel_search";
    public const string LoadSmartFoldersMethod = "load_smart_folders";
    public const string SaveSmartFolderMethod = "save_smart_folder";
    public const string DeleteSmartFolderMethod = "delete_smart_folder";
    public const string OpenFileWithMethod = "open_file_with";
    public const string CompareFilesMethod = "compare_files";
    public const string DiskCleanupMethod = "disk_cleanup";
    public const string CancelDiskCleanupMethod = "cancel_disk_cleanup";
    public const string DuplicateCheckMethod = "duplicate_check";
    public const string CancelDuplicateCheckMethod = "cancel_duplicate_check";
    public const string GetGitStatusMethod = "get_git_status";
    public const string ComputeChecksumMethod = "compute_checksum";
    public const string GetImageMetadataMethod = "get_image_metadata";
    public const string GetFileMetadataMethod = "get_file_metadata";
    public const string GetAppVersionMethod = "get_app_version";
    public const string GetAppAboutInfoMethod = "get_app_about_info";
    public const string CheckForUpdateMethod = "check_for_update";
    public const string InstallUpdateMethod = "install_update";
    public const string ShowMainWindowMethod = "show_main_window";
    public const string GetGitFileStatusesMethod = "get_git_file_statuses";
    public const string GetAllTagsMethod = "get_all_tags";
    public const string CreateTagMethod = "create_tag";
    public const string UpdateTagMethod = "update_tag";
    public const string DeleteTagMethod = "delete_tag";
    public const string SetTagsForPathMethod = "set_tags_for_path";
    public const string GetTagsForPathMethod = "get_tags_for_path";
    public const string GetAllFileTagsMethod = "get_all_file_tags";
    public const string GetFilesWithTagMethod = "get_files_with_tag";

    public const string FileChangeEvent = "file-change";
    public const string OperationProgressEvent = "operation-progress";
    public const string SearchResultsBatchEvent = "search-results-batch";
    public const string SearchCompleteEvent = "search-complete";
    public const string UpdateChunkEvent = "update-chunk";
    public const string ListDirectoryChunkEvent = "list_directory.chunk";

    public static IReadOnlyList<string> DomainMethods { get; } =
    [
        "get_home_dir",
        "select_directory",
        "list_drives",
        "list_directory",
        "list_subdirectories",
        "create_directory",
        "create_file",
        "create_shortcut",
        "delete_entry",
        "move_to_trash",
        "restore_recycle_bin",
        "empty_recycle_bin",
        "rename_entry",
        "batch_rename",
        "copy_entry",
        "move_entry",
        "copy_entry_resolved",
        "move_entry_resolved",
        "get_entry_info",
        "copy_with_progress",
        "move_with_progress",
        "cancel_operation",
        "watch_directory",
        "unwatch_directory",
        "read_file_preview",
        "generate_thumbnail",
        "generate_thumbnails",
        "calculate_folder_size",
        "count_folder_items",
        "get_folder_metrics",
        "cancel_folder_size",
        "cancel_folder_item_count",
        "cancel_count_items",
        "cancel_folder_metrics",
        "open_file",
        "reveal_in_folder",
        "open_external_url",
        "list_archive",
        "extract_archive",
        "create_archive",
        "check_rar_installed",
        "prepare_rar_install",
        "discard_rar_install",
        "install_rar",
        "get_db_setting",
        "set_db_setting",
        "git_pull",
        "git_push",
        "open_terminal",
        "open_powershell_admin",
        "search_files",
        "cancel_search",
        "load_smart_folders",
        "save_smart_folder",
        "delete_smart_folder",
        "open_file_with",
        "compare_files",
        "disk_cleanup",
        "cancel_disk_cleanup",
        "duplicate_check",
        "cancel_duplicate_check",
        "get_git_status",
        "compute_checksum",
        "get_image_metadata",
        "get_file_metadata",
        "get_app_version",
        "get_app_about_info",
        "check_for_update",
        "install_update",
        "show_main_window",
        "get_git_file_statuses",
        "get_all_tags",
        "create_tag",
        "update_tag",
        "delete_tag",
        "set_tags_for_path",
        "get_tags_for_path",
        "get_all_file_tags",
        "get_files_with_tag",
    ];

    public static IReadOnlyList<string> HostOwnedMethods { get; } =
    [
        "select_directory",
        "show_main_window",
    ];

    public static IReadOnlyList<string> CancellationMethods { get; } =
    [
        "cancel_operation",
        "cancel_folder_size",
        "cancel_folder_item_count",
        "cancel_count_items",
        "cancel_folder_metrics",
        "cancel_search",
        "cancel_disk_cleanup",
        "cancel_duplicate_check",
    ];

    public static IReadOnlyList<(string Name, byte Tag)> BinaryFrameMethodTags { get; } =
    [
        ("list_directory.chunk", BinaryListDirectoryChunk),
        ("list_directory.result", BinaryListDirectoryResult),
        ("search_files.batch", BinarySearchResultsBatch),
        ("search_files.result", BinarySearchResultsResult),
        ("generate_thumbnail.result", BinaryThumbnailResult),
        ("generate_thumbnails.result", BinaryThumbnailsResult),
    ];

    public static IReadOnlyList<(string Name, byte Tag)> BinaryFrameEventTags { get; } =
    [
        ("file-change", BinaryFileChange),
        ("operation-progress", BinaryOperationProgress),
        ("search-results-batch", BinarySearchResultsBatch),
        ("list_directory.chunk", BinaryListDirectoryChunk),
    ];
}
