//! Generated IPC protocol metadata.
//!
//! Generated by scripts/generate-ipc-bindings.mjs from ipc/schema/v1.

pub const DOMAIN_METHOD_COUNT: usize = 79;

pub const BINARY_LIST_DIRECTORY_CHUNK: u8 = 1;
pub const BINARY_LIST_DIRECTORY_RESULT: u8 = 2;
pub const BINARY_SEARCH_RESULTS_BATCH: u8 = 3;
pub const BINARY_SEARCH_RESULTS_RESULT: u8 = 4;
pub const BINARY_OPERATION_PROGRESS: u8 = 5;
pub const BINARY_FILE_CHANGE: u8 = 6;
pub const BINARY_THUMBNAIL_RESULT: u8 = 7;
pub const BINARY_THUMBNAILS_RESULT: u8 = 8;

pub const HANDSHAKE_METHOD: &str = "ipc.handshake";
pub const HEALTH_METHOD: &str = "ipc.health";
pub const SHUTDOWN_METHOD: &str = "ipc.shutdown";
pub const FILE_CHANGE: &str = "file-change";
pub const OPERATION_PROGRESS: &str = "operation-progress";
pub const SEARCH_RESULTS_BATCH: &str = "search-results-batch";
pub const SEARCH_COMPLETE: &str = "search-complete";
pub const UPDATE_CHUNK: &str = "update-chunk";
pub const LIST_DIRECTORY_CHUNK: &str = "list_directory.chunk";
pub const METHOD_GET_HOME_DIR: &str = "get_home_dir";
pub const METHOD_SELECT_DIRECTORY: &str = "select_directory";
pub const METHOD_LIST_DRIVES: &str = "list_drives";
pub const METHOD_LIST_DIRECTORY: &str = "list_directory";
pub const METHOD_LIST_SUBDIRECTORIES: &str = "list_subdirectories";
pub const METHOD_CREATE_DIRECTORY: &str = "create_directory";
pub const METHOD_CREATE_FILE: &str = "create_file";
pub const METHOD_CREATE_SHORTCUT: &str = "create_shortcut";
pub const METHOD_DELETE_ENTRY: &str = "delete_entry";
pub const METHOD_MOVE_TO_TRASH: &str = "move_to_trash";
pub const METHOD_RESTORE_RECYCLE_BIN: &str = "restore_recycle_bin";
pub const METHOD_EMPTY_RECYCLE_BIN: &str = "empty_recycle_bin";
pub const METHOD_RENAME_ENTRY: &str = "rename_entry";
pub const METHOD_BATCH_RENAME: &str = "batch_rename";
pub const METHOD_COPY_ENTRY: &str = "copy_entry";
pub const METHOD_MOVE_ENTRY: &str = "move_entry";
pub const METHOD_COPY_ENTRY_RESOLVED: &str = "copy_entry_resolved";
pub const METHOD_MOVE_ENTRY_RESOLVED: &str = "move_entry_resolved";
pub const METHOD_GET_ENTRY_INFO: &str = "get_entry_info";
pub const METHOD_COPY_WITH_PROGRESS: &str = "copy_with_progress";
pub const METHOD_MOVE_WITH_PROGRESS: &str = "move_with_progress";
pub const METHOD_CANCEL_OPERATION: &str = "cancel_operation";
pub const METHOD_WATCH_DIRECTORY: &str = "watch_directory";
pub const METHOD_UNWATCH_DIRECTORY: &str = "unwatch_directory";
pub const METHOD_READ_FILE_PREVIEW: &str = "read_file_preview";
pub const METHOD_GENERATE_THUMBNAIL: &str = "generate_thumbnail";
pub const METHOD_GENERATE_THUMBNAILS: &str = "generate_thumbnails";
pub const METHOD_CALCULATE_FOLDER_SIZE: &str = "calculate_folder_size";
pub const METHOD_COUNT_FOLDER_ITEMS: &str = "count_folder_items";
pub const METHOD_GET_FOLDER_METRICS: &str = "get_folder_metrics";
pub const METHOD_CANCEL_FOLDER_SIZE: &str = "cancel_folder_size";
pub const METHOD_CANCEL_FOLDER_ITEM_COUNT: &str = "cancel_folder_item_count";
pub const METHOD_CANCEL_COUNT_ITEMS: &str = "cancel_count_items";
pub const METHOD_CANCEL_FOLDER_METRICS: &str = "cancel_folder_metrics";
pub const METHOD_OPEN_FILE: &str = "open_file";
pub const METHOD_REVEAL_IN_FOLDER: &str = "reveal_in_folder";
pub const METHOD_OPEN_EXTERNAL_URL: &str = "open_external_url";
pub const METHOD_LIST_ARCHIVE: &str = "list_archive";
pub const METHOD_EXTRACT_ARCHIVE: &str = "extract_archive";
pub const METHOD_CREATE_ARCHIVE: &str = "create_archive";
pub const METHOD_CHECK_RAR_INSTALLED: &str = "check_rar_installed";
pub const METHOD_PREPARE_RAR_INSTALL: &str = "prepare_rar_install";
pub const METHOD_DISCARD_RAR_INSTALL: &str = "discard_rar_install";
pub const METHOD_INSTALL_RAR: &str = "install_rar";
pub const METHOD_GET_DB_SETTING: &str = "get_db_setting";
pub const METHOD_SET_DB_SETTING: &str = "set_db_setting";
pub const METHOD_GIT_PULL: &str = "git_pull";
pub const METHOD_GIT_PUSH: &str = "git_push";
pub const METHOD_OPEN_TERMINAL: &str = "open_terminal";
pub const METHOD_OPEN_POWERSHELL_ADMIN: &str = "open_powershell_admin";
pub const METHOD_SEARCH_FILES: &str = "search_files";
pub const METHOD_CANCEL_SEARCH: &str = "cancel_search";
pub const METHOD_LOAD_SMART_FOLDERS: &str = "load_smart_folders";
pub const METHOD_SAVE_SMART_FOLDER: &str = "save_smart_folder";
pub const METHOD_DELETE_SMART_FOLDER: &str = "delete_smart_folder";
pub const METHOD_OPEN_FILE_WITH: &str = "open_file_with";
pub const METHOD_COMPARE_FILES: &str = "compare_files";
pub const METHOD_DISK_CLEANUP: &str = "disk_cleanup";
pub const METHOD_CANCEL_DISK_CLEANUP: &str = "cancel_disk_cleanup";
pub const METHOD_DUPLICATE_CHECK: &str = "duplicate_check";
pub const METHOD_CANCEL_DUPLICATE_CHECK: &str = "cancel_duplicate_check";
pub const METHOD_GET_GIT_STATUS: &str = "get_git_status";
pub const METHOD_COMPUTE_CHECKSUM: &str = "compute_checksum";
pub const METHOD_GET_IMAGE_METADATA: &str = "get_image_metadata";
pub const METHOD_GET_FILE_METADATA: &str = "get_file_metadata";
pub const METHOD_GET_APP_VERSION: &str = "get_app_version";
pub const METHOD_GET_APP_ABOUT_INFO: &str = "get_app_about_info";
pub const METHOD_CHECK_FOR_UPDATE: &str = "check_for_update";
pub const METHOD_INSTALL_UPDATE: &str = "install_update";
pub const METHOD_SHOW_MAIN_WINDOW: &str = "show_main_window";
pub const METHOD_GET_GIT_FILE_STATUSES: &str = "get_git_file_statuses";
pub const METHOD_GET_ALL_TAGS: &str = "get_all_tags";
pub const METHOD_CREATE_TAG: &str = "create_tag";
pub const METHOD_UPDATE_TAG: &str = "update_tag";
pub const METHOD_DELETE_TAG: &str = "delete_tag";
pub const METHOD_SET_TAGS_FOR_PATH: &str = "set_tags_for_path";
pub const METHOD_GET_TAGS_FOR_PATH: &str = "get_tags_for_path";
pub const METHOD_GET_ALL_FILE_TAGS: &str = "get_all_file_tags";
pub const METHOD_GET_FILES_WITH_TAG: &str = "get_files_with_tag";

pub const DOMAIN_METHODS: &[&str] = &[
    METHOD_GET_HOME_DIR,
    METHOD_SELECT_DIRECTORY,
    METHOD_LIST_DRIVES,
    METHOD_LIST_DIRECTORY,
    METHOD_LIST_SUBDIRECTORIES,
    METHOD_CREATE_DIRECTORY,
    METHOD_CREATE_FILE,
    METHOD_CREATE_SHORTCUT,
    METHOD_DELETE_ENTRY,
    METHOD_MOVE_TO_TRASH,
    METHOD_RESTORE_RECYCLE_BIN,
    METHOD_EMPTY_RECYCLE_BIN,
    METHOD_RENAME_ENTRY,
    METHOD_BATCH_RENAME,
    METHOD_COPY_ENTRY,
    METHOD_MOVE_ENTRY,
    METHOD_COPY_ENTRY_RESOLVED,
    METHOD_MOVE_ENTRY_RESOLVED,
    METHOD_GET_ENTRY_INFO,
    METHOD_COPY_WITH_PROGRESS,
    METHOD_MOVE_WITH_PROGRESS,
    METHOD_CANCEL_OPERATION,
    METHOD_WATCH_DIRECTORY,
    METHOD_UNWATCH_DIRECTORY,
    METHOD_READ_FILE_PREVIEW,
    METHOD_GENERATE_THUMBNAIL,
    METHOD_GENERATE_THUMBNAILS,
    METHOD_CALCULATE_FOLDER_SIZE,
    METHOD_COUNT_FOLDER_ITEMS,
    METHOD_GET_FOLDER_METRICS,
    METHOD_CANCEL_FOLDER_SIZE,
    METHOD_CANCEL_FOLDER_ITEM_COUNT,
    METHOD_CANCEL_COUNT_ITEMS,
    METHOD_CANCEL_FOLDER_METRICS,
    METHOD_OPEN_FILE,
    METHOD_REVEAL_IN_FOLDER,
    METHOD_OPEN_EXTERNAL_URL,
    METHOD_LIST_ARCHIVE,
    METHOD_EXTRACT_ARCHIVE,
    METHOD_CREATE_ARCHIVE,
    METHOD_CHECK_RAR_INSTALLED,
    METHOD_PREPARE_RAR_INSTALL,
    METHOD_DISCARD_RAR_INSTALL,
    METHOD_INSTALL_RAR,
    METHOD_GET_DB_SETTING,
    METHOD_SET_DB_SETTING,
    METHOD_GIT_PULL,
    METHOD_GIT_PUSH,
    METHOD_OPEN_TERMINAL,
    METHOD_OPEN_POWERSHELL_ADMIN,
    METHOD_SEARCH_FILES,
    METHOD_CANCEL_SEARCH,
    METHOD_LOAD_SMART_FOLDERS,
    METHOD_SAVE_SMART_FOLDER,
    METHOD_DELETE_SMART_FOLDER,
    METHOD_OPEN_FILE_WITH,
    METHOD_COMPARE_FILES,
    METHOD_DISK_CLEANUP,
    METHOD_CANCEL_DISK_CLEANUP,
    METHOD_DUPLICATE_CHECK,
    METHOD_CANCEL_DUPLICATE_CHECK,
    METHOD_GET_GIT_STATUS,
    METHOD_COMPUTE_CHECKSUM,
    METHOD_GET_IMAGE_METADATA,
    METHOD_GET_FILE_METADATA,
    METHOD_GET_APP_VERSION,
    METHOD_GET_APP_ABOUT_INFO,
    METHOD_CHECK_FOR_UPDATE,
    METHOD_INSTALL_UPDATE,
    METHOD_SHOW_MAIN_WINDOW,
    METHOD_GET_GIT_FILE_STATUSES,
    METHOD_GET_ALL_TAGS,
    METHOD_CREATE_TAG,
    METHOD_UPDATE_TAG,
    METHOD_DELETE_TAG,
    METHOD_SET_TAGS_FOR_PATH,
    METHOD_GET_TAGS_FOR_PATH,
    METHOD_GET_ALL_FILE_TAGS,
    METHOD_GET_FILES_WITH_TAG,
];

pub const HOST_OWNED_METHODS: &[&str] = &[METHOD_SELECT_DIRECTORY, METHOD_SHOW_MAIN_WINDOW];

pub const CANCELLATION_METHODS: &[&str] = &[
    METHOD_CANCEL_OPERATION,
    METHOD_CANCEL_FOLDER_SIZE,
    METHOD_CANCEL_FOLDER_ITEM_COUNT,
    METHOD_CANCEL_COUNT_ITEMS,
    METHOD_CANCEL_FOLDER_METRICS,
    METHOD_CANCEL_SEARCH,
    METHOD_CANCEL_DISK_CLEANUP,
    METHOD_CANCEL_DUPLICATE_CHECK,
];

pub const BINARY_FRAME_METHOD_TAGS: &[(&str, u8)] = &[
    ("list_directory.chunk", BINARY_LIST_DIRECTORY_CHUNK),
    ("list_directory.result", BINARY_LIST_DIRECTORY_RESULT),
    ("search_files.batch", BINARY_SEARCH_RESULTS_BATCH),
    ("search_files.result", BINARY_SEARCH_RESULTS_RESULT),
    ("generate_thumbnail.result", BINARY_THUMBNAIL_RESULT),
    ("generate_thumbnails.result", BINARY_THUMBNAILS_RESULT),
];

pub const BINARY_FRAME_EVENT_TAGS: &[(&str, u8)] = &[
    (FILE_CHANGE, BINARY_FILE_CHANGE),
    (OPERATION_PROGRESS, BINARY_OPERATION_PROGRESS),
    (SEARCH_RESULTS_BATCH, BINARY_SEARCH_RESULTS_BATCH),
    (LIST_DIRECTORY_CHUNK, BINARY_LIST_DIRECTORY_CHUNK),
];

pub fn is_control_method(method: &str) -> bool {
    method == HANDSHAKE_METHOD || method == HEALTH_METHOD || method == SHUTDOWN_METHOD
}

pub fn is_domain_method(method: &str) -> bool {
    DOMAIN_METHODS.contains(&method)
}
